import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";
import { DisabledraftButton } from "@/components/DisableDraftMode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
        <body>
          {(await draftMode()).isEnabled && (
            <>
              <DisabledraftButton />
              <VisualEditing/>
            </>
          )}
          <main className="py-2 px-4">
            <Header/>
 {children}
          </main>
          <SanityLive/>
      </body>
      </html>
      </ClerkProvider>
  );
}
